apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh -c "{{ .Values.command }}"
          ports:
            - containerPort: 8000
              #envFrom:
              #- fileRef:
              #  name: {{ .Values.envFile }}  # Ajustez cette référence selon la manière dont vous souhaitez gérer les fichiers `.env`
          volumeMounts:
            - mountPath: /app
              name: app-volume
      volumes:
        - name: app-volume
          hostPath:
            path: ./users
            type: Directory

